version: '3'
services:
  postgres-dev:
    image: postgres
    container_name: db-dev
    ports:
      - 5431:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  postgres-test:
    image: postgres
    container_name: db-test
    ports:
      - 5435:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: 